Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using SpendsDemo.Models;
using SpendsDemo.Helpers;
using System.Security.Claims;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace SpendsDemo.Controllers
{
    public class HomeController : Controller
    {
		private readonly UserManager<IdentityUser> _userManager;
		private readonly RoleManager<IdentityRole> _roleManager;
		private readonly IDemoHelper _h;
		private readonly SpendsContext _sc;
		
		public HomeController(UserManager<IdentityUser> um, RoleManager<IdentityRole> rm, IDemoHelper helper, SpendsContext spendsContext)
		{
			_userManager = um;
			_roleManager = rm;
			_h = helper;
			_sc = spendsContext;
		}
		
		[AllowAnonymous]
        public async Task<IActionResult> Index()
        {
			var user = await _userManager.GetUserAsync(HttpContext.User);
			//var role = _h.getRole(_userManager,user.Email); 
			//ViewData["roles"] = roles; 
			
			IQueryable<Spends> sp = from m in _sc.Spends
							  select m;
							  
			IQueryable<string> monthQuery = from m in _sc.Spends
							  select m.TransactionDate.ToString("m-Y");
            
						  
			//List<Spends> spendsList = await yearlySalesQuery.ToListAsync();
			
			var spendsCategoryVM = new SpendsCategoryViewModel
			{
				Spends = await sp.ToListAsync(),
				Months = await monthQuery.Distinct().ToListAsync(),
			};
            return View(spendsCategoryVM);
        }
		
        // GET: Home/LinqTest
        
		public async Task<IActionResult> LinqTest(string x, string y, string qtype, string ctype)
        {
			string errorString = "no errors here";
			errorString = "";
			
			var spendsCategoryVM = new SpendsCategoryViewModel();
			
            if (x == null || y == null || qtype == null || ctype == null)
            {
				errorString = "Invalid number of query requirements";
            }
			else
			{
			    if(qtype == "total")
				{
					var totals = _h.getTotals(_sc,x);
					spendsCategoryVM.SpendSums = totals;
				    spendsCategoryVM.XVals = new List<string>();
				    spendsCategoryVM.YVals = new List<string>();
				}
				
				else if(qtype == "comparison")
				{
			       if(y == "totalspend" || y == "spend")
			       {
				      var ss = _h.getSpendSums(_sc,x);
				      spendsCategoryVM.SpendSums = ss;
				      spendsCategoryVM.XVals = new List<string>();
				      spendsCategoryVM.YVals = new List<string>();
			       }
			       else
			       {
				      spendsCategoryVM.SpendSums = new List<SpendSums>();
			          IQueryable<string>[] queries = _h.getQuery(_sc,x,y,ctype);
				      spendsCategoryVM.XVals = await queries[0].ToListAsync();
				      spendsCategoryVM.YVals = await queries[1].ToListAsync();
			       }
				}
			}
			
			spendsCategoryVM.ErrorString = errorString;
			spendsCategoryVM.CType = ctype;
			
            return View(spendsCategoryVM);
        }
		
		// GET: Home/gb
        public async Task<IActionResult> GB()
        {
			string errorString = "";
				
			
			var query = from c in _sc.Spends
				           group c by new {c.Advertizer, c.Media} into g
						   select new{
							 XKey = g.Key.Advertizer,
							 YKey = g.Key.Media,
                             TCount = g.Count()							 
						   }; 
			
        	var ret = await query.ToListAsync();
			List<SpendComparisons> sc = new List<SpendComparisons>();
			
			foreach(var r in ret)
			{
				sc.Add(new SpendComparisons{
					       XKey = r.XKey.ToString(),
					       YKey = r.YKey.ToString(),
                           TCount = r.TCount						   
					 });
			}
			
            return View(sc);
        }


        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/SpendsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using SpendsDemo.Models;
using SpendsDemo.Helpers;
using System.Text;
using System.IO;

namespace SpendsDemo.Controllers
{
    public class SpendsController : Controller
    {
        private readonly SpendsContext _context;
        private readonly IDemoHelper _h;
        private readonly IHostingEnvironment _e;

        public SpendsController(SpendsContext context,IDemoHelper helper, IHostingEnvironment env)
        {
            _context = context;
			_h = helper;
			_e = env;
        }

        // GET: Spends
        public async Task<IActionResult> Index()
        {
            return View(await _context.Spends.ToListAsync());
        }

        // GET: Spends/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var spends = await _context.Spends
                .FirstOrDefaultAsync(m => m.Id == id);
            if (spends == null)
            {
                return NotFound();
            }

            return View(spends);
        }
		

        // GET: Spends/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Spends/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Media,Region,Quarter,Category,Advertizer,Brand,Station,TVRadio,Days,TransactionDate,TimeBand,TimeSlot,Print,AverageDuration,AdSize,TotalSpend,DateAdded")] Spends spends)
        {
            if (ModelState.IsValid)
            {
                _context.Add(spends);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(spends);
        }

        // GET: Spends/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var spends = await _context.Spends.FindAsync(id);
            if (spends == null)
            {
                return NotFound();
            }
            return View(spends);
        }

        // POST: Spends/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,Name,Media,Region,Quarter,Category,Advertizer,Brand,Station,TVRadio,Days,TransactionDate,TimeBand,TimeSlot,Print,AverageDuration,AdSize,TotalSpend,DateAdded")] Spends spends)
        {
            if (id != spends.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(spends);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SpendsExists(spends.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(spends);
        }

        // GET: Spends/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var spends = await _context.Spends
                .FirstOrDefaultAsync(m => m.Id == id);
            if (spends == null)
            {
                return NotFound();
            }

            return View(spends);
        }

        // POST: Spends/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var spends = await _context.Spends.FindAsync(id);
            _context.Spends.Remove(spends);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SpendsExists(string id)
        {
            return _context.Spends.Any(e => e.Id == id);
        }
    }
}

Views/Home/GB.cshtml
@model List<SpendComparisons>

@{
    ViewData["Title"] = "Query Test Page";
}

<div class="row">
<div class="col-lg-12">
<h4>Sums for totalspends</h4>
<ul>
@foreach(var r in Model){
<li>[@r.XKey ==> @r.YKey] ===> @r.TCount</li>
}
</ul>
</div>
</div>

Views/Home/Index.cshtml
@model SpendsDemo.Models.SpendsCategoryViewModel

@{
    ViewData["Title"] = "Home Page";
}


<form id="dt-1">
@foreach(var item in Model.Spends){
<input type="hidden" data-month="@Html.DisplayFor(modelItem => item.TransactionDate)" data-media="@Html.DisplayFor(modelItem => item.Media)" data-id="@Html.DisplayFor(modelItem => item.Id)" data-name="@Html.DisplayFor(modelItem => item.Name)" data-spend="@Html.DisplayFor(modelItem => item.TotalSpend)">
}
</form>

<form id="dt-month">
@foreach(var item in Model.Months){
<input type="hidden" name="@Html.DisplayFor(modelItem => item)" value="@Html.DisplayFor(modelItem => item)">
}
</form>

<h2 class="text-primary">Visualization Tool 1.0</h2>
                <div class="row">
                    <div class="col-lg-6">
                        <div class="card">
                            <div class="card-title">
                                <h4>Yearly Sales </h4>

                            </div>
                            <div class="sales-chart">
                                <canvas id="sales-chart"></canvas>
                            </div>
                        </div>
                    </div>
                    <!-- /# column -->
                    <div class="col-lg-6">
                        <div class="card">
                            <div class="card-title">
                                <h4>Total Spends From Jan to Feb 2016 </h4>

                            </div>
                            <div class="sales-chart">
                                <canvas id="team-chart"></canvas>
                            </div>
                        </div>
                        <!-- /# card -->
                    </div>
                    <!-- /# column -->
                </div>
                <!-- /# row -->
                <div class="row">
                    <!-- Bar Chart -->
                    <div class="col-sm-12 col-md-6">
                        <div class="panel">
                            <div class="panel-heading">
                                <div class="panel-title">
                                    <h4>Bar chart</h4>
                                </div>
                            </div>
                            <div class="panel-body">
                                <canvas id="barChart"></canvas>
                            </div>
                        </div>
                    </div>
                    <!-- Radar Chart -->
                    <div class="col-sm-12 col-md-6">
                        <div class="panel">
                            <div class="panel-heading">
                                <div class="panel-title">
                                    <h4>Rader chart</h4>
                                </div>
                            </div>
                            <div class="panel-body">
                                <canvas id="radarChart"></canvas>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <!-- Line Chart -->
                    <div class="col-sm-12 col-md-8">
                        <div class="panel panel-bd lobidrag">
                            <div class="panel-heading">
                                <div class="panel-title">
                                    <h4>Line chart</h4>
                                </div>
                            </div>
                            <div class="panel-body">
                                <canvas id="lineChart"></canvas>
                            </div>
                        </div>
                    </div>
                    <!-- Pie Chart -->
                    <div class="col-sm-6 col-md-4">
                        <div class="panel">
                            <div class="panel-heading">
                                <div class="panel-title">
                                    <h4>Pie chart</h4>
                                </div>
                            </div>
                            <div class="panel-body">
                                <canvas id="pieChart"></canvas>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <!-- Doughnut Chart -->
                    <div class="col-sm-6 col-md-4">
                        <div class="panel">
                            <div class="panel-heading">
                                <div class="panel-title">
                                    <h4>Doughut chart</h4>
                                </div>
                            </div>
                            <div class="panel-body">
                                <canvas id="doughutChart"></canvas>
                            </div>
                        </div>
                    </div>
                    <!-- Polar Chart -->
                    <div class="col-sm-6 col-md-4">
                        <div class="panel">
                            <div class="panel-heading">
                                <div class="panel-title">
                                    <h4>Polar chart</h4>
                                </div>
                            </div>
                            <div class="panel-body">
                                <canvas id="polarChart"></canvas>
                            </div>
                        </div>
                    </div>
                    <!-- Single Bar Chart -->
                    <div class="col-sm-6 col-md-4">
                        <div class="panel">
                            <div class="panel-heading">
                                <div class="panel-title">
                                    <h4>Single Bar Chart</h4>
                                </div>
                            </div>
                            <div class="panel-body">
                                <canvas id="singelBarChart"></canvas>
                            </div>
                        </div>
                    </div>
                </div>
				

@section Scripts{
   <script src="~/js/lib/chart-js/Chart.bundle.js"></script>
    <script src="~/js/lib/chart-js/chartjs-init.js" asp-append-version="true"></script>
}

Views/Home/LinqTest.cshtml
@model SpendsDemo.Models.SpendsCategoryViewModel


@{
    ViewData["Title"] = "Home Page";
}

<div class="row">
<div class="col-lg-12">
<form asp-controller="Spends" asp-action="linqtest">
  <div class="form-group">
     <label for="qtype">Enter query type:</label>
     <select class="form-control" name="qtype" id="qtype">
	   <option value="none">Select query type</option>
	   <option value="total">Total</option>
	   <option value="comparison">Compare</option>
	 </select>
  </div>
   <div class="form-group" id="fg-x">
     <label for="x">Select property for X values:</label>
     <select class="form-control" name="x">
	   <option value="none">Select property for X values</option>
	   <option value="date">Date</option>
	   <option value="brand">Brand</option>
	   <option value="category">Category</option>
	   <option value="media">Media</option>
	   <option value="region">Region</option>
	   <option value="quarter">Quarter</option>
	   <option value="advertizer">Advertizer</option>
	   <option value="station">Station</option>
	   <option value="tvradio">TV/Radio</option>
	   <option value="days">Days</option>
	   <option value="timeband">Time band</option>
	   <option value="timeslot">Time slot</option>
	   <option value="print">Print</option>
	   <option value="duration">Average duration</option>
	   <option value="adsize">Ad size</option>
	 </select>
   </div>
   <div class="form-group" id="fg-y">
     <label for="y">Select property for Y values:</label>
     <select class="form-control" name="y">
	   <option value="none">Select property for Y values</option>
	   <option value="totalspend">Spend</option>
	   <option value="brand">Brand</option>
	   <option value="category">Category</option>
	   <option value="media">Media</option>
	   <option value="quarter">Quarter</option>
	   <option value="advertizer">Advertizer</option>
	   <option value="station">Station</option>
	   <option value="tvradio">TV/Radio</option>
	   <option value="days">Days</option>
	   <option value="timeband">Time band</option>
	   <option value="timeslot">Time slot</option>
	   <option value="print">Print</option>
	   <option value="duration">Average duration</option>
	   <option value="adsize">Ad size</option>
	 </select>
  </div>
  <div class="form-group">
     <label for="ctype">Enter chart type:</label>
     <select class="form-control" name="ctype">
	   <option value="none">Select chart type</option>
	   <option value="bar">Bar chart</option>
	   <option value="line">Line chart</option>
	   <option value="pie">Pie chart</option>
	   <option value="doughnut">Doughnut chart</option>
	 </select>
  </div>
  <div class="form-group">
     <input type="submit" class="btn btn-primary" value="Run Query">
  </div>
</form>
</div>
</div>

@if(Model.ErrorString == ""){
<form id="c-s">
@if(Model.SpendSums.Count > 0){
  for(var i = 0; i < Model.SpendSums.Count; i++){
    <input type="hidden" data-x="@Model.SpendSums[i].PKey" data-y="@Model.SpendSums[i].TSpend" >
  }
}
else{
  for(var i = 0; i < Model.XVals.Count; i++){
    <input type="hidden" data-x="@Model.XVals[i]" data-y="@Model.YVals[i]" >
  }
}
</form>
<div class="row">
<div class="col-lg-6">
  <h3 class="text-info">Search Results</h3>
  <table class="table table-responsive" id="table-linqtest">
    <tr>
	  <th>XVal</th>
	  <th>YVal</th>
	</tr>
	@for(var i = 0; i < Model.XVals.Count; i++){
      <tr>
	    <td>@Model.XVals[i]</td>
        <td>@Model.YVals[i]</td>
	  </tr>
    }
  </table>
  <script> //$('#table-linqtest').DataTable();</script>
</div>
<div class="col-lg-6">
<div class="card">
<div class="card-title">
 <h4>Search Results</h4>

</div>
<div class="linqtest-chart">
    <canvas id="linqtest-chart" data-ctype="@Model.CType"></canvas>
</div>
                        </div>
</div>
</div>

}
else{
<div class="row">
  <div class="col-lg-12">
    <div class="alert alert-danger">@Model.ErrorString</div>
  </div>
</div>
}

@section Scripts{
   <script src="~/js/lib/chart-js/Chart.bundle.js"></script>
    <script src="~/js/lib/chart-js/linqtest-chart-init.js" asp-append-version="true"></script>
}